name: CI check
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      # make depends on poetry
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Run linter
        run: |
          make lint
      - name: Run Tests
        run: |
          make test
      - name: poetry run pytest
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: poetry run pytest --cov=page_loader --cov-report xml tests/
          debug: true